language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
services:
  - postgresql
env:
  - Django==1.6 DB=postgres
before_script:
  - psql -U postgres -c "CREATE USER photorizer WITH PASSWORD 'photorize' SUPERUSER;"
  - createdb photorizedb
  # - cd photorize
# command to run tests
script: cd photorize; python manage.py test --settings=photorize.settings_ghver --configuration=Test
