language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
env:
  - Django==1.6 DB=postgres
# command to run tests
script: python manage.py test
