language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
env:
  - Django==1.6 DB=postgres
before_script:
  # - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database photorizedb;' -U photorizer
  # - cd photorize
# command to run tests
script: cd photorize; python manage.py test
